// Permissions Constants

// Appointment Permissions
export const PERMISSION_APPOINTMENT_CREATE = 'appointment:create';
export const PERMISSION_APPOINTMENT_READ_OWN = 'appointment:read:own';
export const PERMISSION_APPOINTMENT_READ_ALL = 'appointment:read:all';
export const PERMISSION_APPOINTMENT_UPDATE_OWN = 'appointment:update:own';
export const PERMISSION_APPOINTMENT_UPDATE_ALL = 'appointment:update:all';
export const PERMISSION_APPOINTMENT_CANCEL_OWN = 'appointment:cancel:own';
export const PERMISSION_APPOINTMENT_CANCEL_ALL = 'appointment:cancel:all';
export const PERMISSION_APPOINTMENT_DELETE = 'appointment:delete';

// Consultation Permissions
export const PERMISSION_CONSULTATION_CREATE = 'consultation:create';
export const PERMISSION_CONSULTATION_READ_OWN = 'consultation:read:own';
export const PERMISSION_CONSULTATION_READ_ALL = 'consultation:read:all';
export const PERMISSION_CONSULTATION_UPDATE_OWN = 'consultation:update:own';
export const PERMISSION_CONSULTATION_UPDATE_ALL = 'consultation:update:all';

// Prescription Permissions
export const PERMISSION_PRESCRIPTION_CREATE = 'prescription:create';
export const PERMISSION_PRESCRIPTION_READ_OWN = 'prescription:read:own';
export const PERMISSION_PRESCRIPTION_READ_ALL = 'prescription:read:all';
export const PERMISSION_PRESCRIPTION_UPDATE_OWN = 'prescription:update:own';
export const PERMISSION_PRESCRIPTION_UPDATE_ALL = 'prescription:update:all';
export const PERMISSION_PRESCRIPTION_DELETE = 'prescription:delete';
export const PERMISSION_PRESCRIPTION_REFILL_REQUEST = 'prescription:refill:request';
export const PERMISSION_PRESCRIPTION_VERIFY = 'prescription:verify';

// Order Permissions
export const PERMISSION_ORDER_CREATE = 'order:create';
export const PERMISSION_ORDER_READ_OWN = 'order:read:own';
export const PERMISSION_ORDER_READ_ALL = 'order:read:all';
export const PERMISSION_ORDER_UPDATE_OWN = 'order:update:own';
export const PERMISSION_ORDER_UPDATE_ALL = 'order:update:all';
export const PERMISSION_ORDER_CANCEL_OWN = 'order:cancel:own';
export const PERMISSION_ORDER_CANCEL_ALL = 'order:cancel:all';
export const PERMISSION_ORDER_DELETE = 'order:delete';

// Inventory Permissions
export const PERMISSION_INVENTORY_READ_ALL = 'inventory:read:all';
export const PERMISSION_INVENTORY_UPDATE_ALL = 'inventory:update:all';

// Delivery Permissions
export const PERMISSION_DELIVERY_UPDATE = 'delivery:update';
export const PERMISSION_DELIVERY_READ_ALL = 'delivery:read:all';

// Wallet Permissions
export const PERMISSION_WALLET_READ_OWN = 'wallet:read:own';
export const PERMISSION_WALLET_READ_ALL = 'wallet:read:all';
export const PERMISSION_WALLET_TOPUP = 'wallet:topup';
export const PERMISSION_WALLET_WITHDRAW = 'wallet:withdraw';
export const PERMISSION_WALLET_UPDATE_ALL = 'wallet:update:all';

// Insurance Permissions
export const PERMISSION_INSURANCE_READ_OWN = 'insurance:read:own';
export const PERMISSION_INSURANCE_READ_ALL = 'insurance:read:all';
export const PERMISSION_INSURANCE_UPDATE_ALL = 'insurance:update:all';
export const PERMISSION_INSURANCE_DELETE = 'insurance:delete';
export const PERMISSION_INSURANCE_CLAIM_SUBMIT = 'insurance:claim:submit';

// User Permissions
export const PERMISSION_USER_CREATE = 'user:create';
export const PERMISSION_USER_READ_ALL = 'user:read:all';
export const PERMISSION_USER_UPDATE_ALL = 'user:update:all';
export const PERMISSION_USER_DELETE_ALL = 'user:delete:all';
export const PERMISSION_USER_VERIFY = 'user:verify';

// Profile Permissions
export const PERMISSION_PROFILE_READ_OWN = 'profile:read:own';
export const PERMISSION_PROFILE_UPDATE_OWN = 'profile:update:own';

// Patient Permissions
export const PERMISSION_PATIENT_READ_ALL = 'patient:read:all';
export const PERMISSION_PATIENT_HISTORY_READ = 'patient:history:read';

// Doctor Permissions
export const PERMISSION_DOCTOR_VERIFY = 'doctor:verify';
export const PERMISSION_SCHEDULE_READ_OWN = 'schedule:read:own';
export const PERMISSION_SCHEDULE_UPDATE_OWN = 'schedule:update:own';
export const PERMISSION_REVIEW_READ_OWN = 'review:read:own';

// Pharmacy Permissions
export const PERMISSION_PHARMACY_VERIFY = 'pharmacy:verify';

// Notification Permissions
export const PERMISSION_NOTIFICATION_READ_OWN = 'notification:read:own';
export const PERMISSION_NOTIFICATION_READ_ALL = 'notification:read:all';
export const PERMISSION_NOTIFICATION_UPDATE_OWN = 'notification:update:own';
export const PERMISSION_NOTIFICATION_UPDATE_ALL = 'notification:update:all';
export const PERMISSION_NOTIFICATION_SEND_ALL = 'notification:send:all';

// Settings Permissions
export const PERMISSION_SETTINGS_READ = 'settings:read';
export const PERMISSION_SETTINGS_UPDATE = 'settings:update';

// Report Permissions
export const PERMISSION_REPORT_READ_ALL = 'report:read:all';

// Audit Permissions
export const PERMISSION_AUDIT_READ_ALL = 'audit:read:all';

// All Permissions Array
export const ALL_PERMISSIONS = [
  // Appointment
  PERMISSION_APPOINTMENT_CREATE,
  PERMISSION_APPOINTMENT_READ_OWN,
  PERMISSION_APPOINTMENT_READ_ALL,
  PERMISSION_APPOINTMENT_UPDATE_OWN,
  PERMISSION_APPOINTMENT_UPDATE_ALL,
  PERMISSION_APPOINTMENT_CANCEL_OWN,
  PERMISSION_APPOINTMENT_CANCEL_ALL,
  PERMISSION_APPOINTMENT_DELETE,
  // Consultation
  PERMISSION_CONSULTATION_CREATE,
  PERMISSION_CONSULTATION_READ_OWN,
  PERMISSION_CONSULTATION_READ_ALL,
  PERMISSION_CONSULTATION_UPDATE_OWN,
  PERMISSION_CONSULTATION_UPDATE_ALL,
  // Prescription
  PERMISSION_PRESCRIPTION_CREATE,
  PERMISSION_PRESCRIPTION_READ_OWN,
  PERMISSION_PRESCRIPTION_READ_ALL,
  PERMISSION_PRESCRIPTION_UPDATE_OWN,
  PERMISSION_PRESCRIPTION_UPDATE_ALL,
  PERMISSION_PRESCRIPTION_DELETE,
  PERMISSION_PRESCRIPTION_REFILL_REQUEST,
  PERMISSION_PRESCRIPTION_VERIFY,
  // Order
  PERMISSION_ORDER_CREATE,
  PERMISSION_ORDER_READ_OWN,
  PERMISSION_ORDER_READ_ALL,
  PERMISSION_ORDER_UPDATE_OWN,
  PERMISSION_ORDER_UPDATE_ALL,
  PERMISSION_ORDER_CANCEL_OWN,
  PERMISSION_ORDER_CANCEL_ALL,
  PERMISSION_ORDER_DELETE,
  // Inventory
  PERMISSION_INVENTORY_READ_ALL,
  PERMISSION_INVENTORY_UPDATE_ALL,
  // Delivery
  PERMISSION_DELIVERY_UPDATE,
  PERMISSION_DELIVERY_READ_ALL,
  // Wallet
  PERMISSION_WALLET_READ_OWN,
  PERMISSION_WALLET_READ_ALL,
  PERMISSION_WALLET_TOPUP,
  PERMISSION_WALLET_WITHDRAW,
  PERMISSION_WALLET_UPDATE_ALL,
  // Insurance
  PERMISSION_INSURANCE_READ_OWN,
  PERMISSION_INSURANCE_READ_ALL,
  PERMISSION_INSURANCE_UPDATE_ALL,
  PERMISSION_INSURANCE_DELETE,
  PERMISSION_INSURANCE_CLAIM_SUBMIT,
  // User
  PERMISSION_USER_CREATE,
  PERMISSION_USER_READ_ALL,
  PERMISSION_USER_UPDATE_ALL,
  PERMISSION_USER_DELETE_ALL,
  PERMISSION_USER_VERIFY,
  // Profile
  PERMISSION_PROFILE_READ_OWN,
  PERMISSION_PROFILE_UPDATE_OWN,
  // Patient
  PERMISSION_PATIENT_READ_ALL,
  PERMISSION_PATIENT_HISTORY_READ,
  // Doctor
  PERMISSION_DOCTOR_VERIFY,
  PERMISSION_SCHEDULE_READ_OWN,
  PERMISSION_SCHEDULE_UPDATE_OWN,
  PERMISSION_REVIEW_READ_OWN,
  // Pharmacy
  PERMISSION_PHARMACY_VERIFY,
  // Notification
  PERMISSION_NOTIFICATION_READ_OWN,
  PERMISSION_NOTIFICATION_READ_ALL,
  PERMISSION_NOTIFICATION_UPDATE_OWN,
  PERMISSION_NOTIFICATION_UPDATE_ALL,
  PERMISSION_NOTIFICATION_SEND_ALL,
  // Settings
  PERMISSION_SETTINGS_READ,
  PERMISSION_SETTINGS_UPDATE,
  // Report
  PERMISSION_REPORT_READ_ALL,
  // Audit
  PERMISSION_AUDIT_READ_ALL,
] as const;

export type Permission = (typeof ALL_PERMISSIONS)[number];

// Permission groups for organization
export const PERMISSION_GROUPS = {
  APPOINTMENT: [
    PERMISSION_APPOINTMENT_CREATE,
    PERMISSION_APPOINTMENT_READ_OWN,
    PERMISSION_APPOINTMENT_READ_ALL,
    PERMISSION_APPOINTMENT_UPDATE_OWN,
    PERMISSION_APPOINTMENT_UPDATE_ALL,
    PERMISSION_APPOINTMENT_CANCEL_OWN,
    PERMISSION_APPOINTMENT_CANCEL_ALL,
    PERMISSION_APPOINTMENT_DELETE,
  ],
  CONSULTATION: [
    PERMISSION_CONSULTATION_CREATE,
    PERMISSION_CONSULTATION_READ_OWN,
    PERMISSION_CONSULTATION_READ_ALL,
    PERMISSION_CONSULTATION_UPDATE_OWN,
    PERMISSION_CONSULTATION_UPDATE_ALL,
  ],
  PRESCRIPTION: [
    PERMISSION_PRESCRIPTION_CREATE,
    PERMISSION_PRESCRIPTION_READ_OWN,
    PERMISSION_PRESCRIPTION_READ_ALL,
    PERMISSION_PRESCRIPTION_UPDATE_OWN,
    PERMISSION_PRESCRIPTION_UPDATE_ALL,
    PERMISSION_PRESCRIPTION_DELETE,
    PERMISSION_PRESCRIPTION_REFILL_REQUEST,
    PERMISSION_PRESCRIPTION_VERIFY,
  ],
  ORDER: [
    PERMISSION_ORDER_CREATE,
    PERMISSION_ORDER_READ_OWN,
    PERMISSION_ORDER_READ_ALL,
    PERMISSION_ORDER_UPDATE_OWN,
    PERMISSION_ORDER_UPDATE_ALL,
    PERMISSION_ORDER_CANCEL_OWN,
    PERMISSION_ORDER_CANCEL_ALL,
    PERMISSION_ORDER_DELETE,
  ],
  INVENTORY: [
    PERMISSION_INVENTORY_READ_ALL,
    PERMISSION_INVENTORY_UPDATE_ALL,
  ],
  DELIVERY: [
    PERMISSION_DELIVERY_UPDATE,
    PERMISSION_DELIVERY_READ_ALL,
  ],
  WALLET: [
    PERMISSION_WALLET_READ_OWN,
    PERMISSION_WALLET_READ_ALL,
    PERMISSION_WALLET_TOPUP,
    PERMISSION_WALLET_WITHDRAW,
    PERMISSION_WALLET_UPDATE_ALL,
  ],
  INSURANCE: [
    PERMISSION_INSURANCE_READ_OWN,
    PERMISSION_INSURANCE_READ_ALL,
    PERMISSION_INSURANCE_UPDATE_ALL,
    PERMISSION_INSURANCE_DELETE,
    PERMISSION_INSURANCE_CLAIM_SUBMIT,
  ],
  USER: [
    PERMISSION_USER_CREATE,
    PERMISSION_USER_READ_ALL,
    PERMISSION_USER_UPDATE_ALL,
    PERMISSION_USER_DELETE_ALL,
    PERMISSION_USER_VERIFY,
  ],
  PROFILE: [
    PERMISSION_PROFILE_READ_OWN,
    PERMISSION_PROFILE_UPDATE_OWN,
  ],
  PATIENT: [
    PERMISSION_PATIENT_READ_ALL,
    PERMISSION_PATIENT_HISTORY_READ,
  ],
  DOCTOR: [
    PERMISSION_DOCTOR_VERIFY,
    PERMISSION_SCHEDULE_READ_OWN,
    PERMISSION_SCHEDULE_UPDATE_OWN,
    PERMISSION_REVIEW_READ_OWN,
  ],
  PHARMACY: [
    PERMISSION_PHARMACY_VERIFY,
  ],
  NOTIFICATION: [
    PERMISSION_NOTIFICATION_READ_OWN,
    PERMISSION_NOTIFICATION_READ_ALL,
    PERMISSION_NOTIFICATION_UPDATE_OWN,
    PERMISSION_NOTIFICATION_UPDATE_ALL,
    PERMISSION_NOTIFICATION_SEND_ALL,
  ],
  SETTINGS: [
    PERMISSION_SETTINGS_READ,
    PERMISSION_SETTINGS_UPDATE,
  ],
  REPORT: [
    PERMISSION_REPORT_READ_ALL,
  ],
  AUDIT: [
    PERMISSION_AUDIT_READ_ALL,
  ],
} as const;
